---
driver:
  name: vagrant
  network:
  - ["public_network", {ip: "192.168.0.203",bridge: "wlan0"}]
  - ["forwarded_port", {guest: 60, host: 6081}]
provisioner:
  name: chef_solo

platforms:
  - name: centos-6.5

suites:
  - name: default
    run_list:
      - recipe[yum-epel::default]
      - recipe[varnish::default]
      - recipe[kini::default]
    attributes:
