default['varnish']['backend_host']="www.resultados-futbol.com"
default['varnish']['backend_port']="80"
default['varnish']['group']="root"
default['varnish']['user']="root"
default['varnish']['ttl']="90"
default['varnish']['host_header']="www.resultados-futbol.com"
default['varnish']['vcl_cookbook']="kini"
default['varnish']['vcl_source']="default.vcl.erb"